name: GitHub Issues Report Generator
on: 
  push:
    branches:
      - develop
#  schedule:
    # Executa às 8:00 de segunda a sexta-feira
#    - cron: '0 8 * * 1-5'
  # Permite execução manual a partir da interface do GitHub
 
jobs:
  generate-report:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
        
    - name: Cache Airbyte DuckDB cache
      uses: actions/cache@v4
      with:
        path: .cache/default_cache
        key: ${{ runner.os }}-airbyte-duckdb
        restore-keys: |
          ${{ runner.os }}-airbyte-duckdb
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests python-dotenv
        pip install -r requirements.txt
    - name: Create .env file
      run: |
        echo "TOKEN=${{ secrets.TOKEN }}" > .env
        echo "REPOSITORY=${{ secrets.REPOSITORY }}" >> .env
          
    - name: Run report generator

      run: python report.py
      
    - name: Commit and push reports
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add *.md
        git commit -m "Atualização automática dos relatórios de issues" || echo "No changes to commit"
        git push
